server.port=8080
spring.application.name=flash
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER_CLASS}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=${MULTIPART_FILE_MAX_SIZE}
spring.servlet.multipart.max-request-size=${MULTIPART_REQUEST_MAX_SIZE}
# Swagger
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.defaultModelExpandDepth=1
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.deepLinking=true
# Scheduler Task settings
scheduler.pool.size=5
scheduler.threadNamePrefix=Scheduler-
scheduler.awaitTerminationSeconds=30
scheduler.waitForTasksToCompleteOnShutdown=true
# JWT
auth.jwt.secret=${JWT_SECRET}
auth.jwt.expiration=${JWT_EXPIRATION}
# AWS
spring.cloud.aws.credentials.access-key=${ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${SECRET_KEY}
spring.cloud.aws.region.static=ap-northeast-2
aws.s3.input-bucket.image=${S3_IMAGE_BUCKET}
aws.s3.input-bucket.video=${S3_VIDEO_INPUT_BUCKET}
aws.s3.output-bucket.video=${S3_VIDEO_OUTPUT_BUCKET}
aws.cdn.domain=${CDN_DOMAIN}
aws.media-convert.role-arn=${MEDIA_CONVERT_ROLE_ARN}
aws.media-convert.queue-arn=${MEDIA_CONVERT_QUEUE_ARN}

